 services:
  - type: web
    name: pairup-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: "https://pairup-webapp.vercel.app/"