services:
  - type: web
    name: pairup-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: "https://your-frontend-url.vercel.app"